  <?php require 'includes/head.php'; ?>
  <?php require 'includes/menu.php'; ?>
  <?php require 'includes/sobre/banner-sobre.php'; ?>
  <?php require 'includes/sobre/video-area-sobre.php'; ?>
  <?php require 'includes/sobre/card-count-sobre.php'; ?>
  <?php require 'includes/sobre/area-quality-sobre.php'; ?>
  <?php require 'includes/home/team-home.php'; ?>
  <?php require 'includes/sobre/testemunho-time.php'; ?>
  <?php require 'includes/sobre/sobre-contact.php'; ?>
  <?php require 'includes/footer.php'; ?>
